### ISSUE TITLE
US Seal Engineer loadout only has 1 magazine

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#312] opened 2016-02-21 11:32 UTC
As title, engineer loadouts for the US Seals only have one magazine.

**Comment by TheGrandVizier** [comment] 2016-02-22 08:19
Is this confirmed?
When I said it in real time in an op, I may have gone through a couple of mags. I was quite intoxicated.
If that was indeed the case, the mag count initially is 3.
Which is what we agreed upon for these loadouts in order to make space for the deployable boxes.

This could be solved by going to MP5's, as their ammo takes less space iirc.

**Comment by TheGrandVizier** [comment] 2016-02-22 08:19
Also, some people called into question the very existence of medical / fob for this faction.

**Comment by ShiFoo** [comment] 2016-02-22 08:38
I will have a look at it, but as far as i have tested it, the boxes fit into the backpack.
Thing is: You only have uniform and backpack... no vest due to the rebreather.

**Comment by Fourjays** [comment] 2016-02-22 10:31
I think switching to MP5s for the SEALs would make sense, especially given the limited space.

**Comment by ShiFoo** [comment] 2016-02-24 08:55
Ok, will switch to MP5's and see how much space is available...

**Comment by ShiFoo** [comment] 2016-03-02 23:07
Changes committed. Closing.

**Closed by ShiFoo** 2016-03-02 23:07 UTC
Labels: Low Priority, Template
