### ISSUE TITLE
Adjustments to FOB and Medical Tent for new Platoon structure

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#349] opened 2016-03-16 00:45 UTC
As a result of planned Platoon structure changes (blackwatchint/modpack#348) we wish toadjust the the FOB and Medical Tent as follows:

- Remove any rules that tie deployment to specific roles.
- Add an option to disable the timer/countdown for respawning players.
- Switch the items to behave as vehicle loadable containers instead of backpack items.
- If possible, have deployment done as an ACE interaction instead of on the scroll menu.

**Comment by ShiFoo** [comment] 2016-03-16 08:11
-Currently, the Toolkit is a requirement to place the FOB/tent. I assume the item requirement shall be removed?
-Point 4 is more a necessity than an option. I dont think adding actions to those crates is a good idea.
-FOB/tent orientation is still a problem. One idea i am currently having is that the constructor can rotate it for a certain period of time after deploying (via scroll menu/ace interact on the tent itself). maybe open a small dialog with a text input for degrees or a slider. Other idea is to simply use the orientation from the box to the player. Then he would need to stand on the side of the box which should be the front facing side.

**Comment by Fourjays** [comment] 2016-03-21 23:37
Toolkit may or may not remain a requirement, depending on exact setup. But most likely will be not.

I know we've had difficulties locating suitable objects. I've had a quick browse through myself and thought maybe one of, or a combination of, these items could be possible: http://steamcommunity.com/sharedfiles/filedetails/?id=650137926

I'd also suggest we try re-texturing the default container labels. The Bundeswehr mod already does this: http://steamcommunity.com/sharedfiles/filedetails/?id=650137970

In the above image, the middle box is the left box with the "label" replaced. The left box is vanilla AAF and the right box is vanilla US. They use the same model but have 2 texture options. AAF uses a white texture and US uses green. They then have a seperate label texture which applies the lettering. In the case of the Bundeswehr one, they've replaced the label texture.

The label textures are subsequently configured using the "AnimationSources" class in the config.cpp. This allows the label texture to be used across different ammobox models and easily switched to another. In this example, the same model is set to be a Support box simply by changing the "animation" state.

```sqf
class AnimationSources
{
	class Ammo_source
	{
		source="user";
		initPhase=1;
		animPeriod=1;
	};
	class AmmoOrd_source
	{
		source="user";
		initPhase=1;
		animPeriod=1;
	};
	class Grenades_source
	{
		source="user";
		initPhase=1;
		animPeriod=1;
	};
	class Support_source
	{
		source="user";
		initPhase=0;
		animPeriod=1;
	};
};
```

**Comment by ShiFoo** [comment] 2016-03-22 09:10
I had the same boxes in mind. The cardbox and the netted box. The problem is that they cannot be dragged or carried. The mass, which is stored inside the model, is too high. Otherwise you could make a building draggable and pull it around the map. Maybe the wooden box for the tent and the greenish ones for the FOB...

I am totally fine with retexturing. Ok, so the texture must be some kind of picture, which is then "wrapped" around the 3D model. I don't see any reference to a .paa in the animationSources... so your snippet cannot be everything needed to retexture. This is where i don't understand how it should work.

**Comment by Fourjays** [comment] 2016-03-22 15:32
The .paa is referenced by overriding hiddenSelectionsTextures in a config inheriting from the vanilla boxes. This allows you to set a custom .paa texture.

```sqf
hiddenSelections[]=
{
    "Camo_Signs",
    "Camo"
};
hiddenSelectionsTextures[]=
{
    "\custom_ammoboxes\data\ammobox_signs.paa",
    "A3\Weapons_F\Ammoboxes\data\AmmoBox_HAF_CO.paa"
};
```

If you think we can use vanilla ammobox models to represent parts of an FOB/tent setup, then I can do a texture replacement for it (already planning to customize the texture on our own ammoboxes, so not difficult to do one that says "FOB" instead of "Ammunition").

**Comment by ShiFoo** [comment] 2016-04-19 17:20
Switched off reinsertion timer if FOB has been disabled by Zeus.
Other topics from the initial post are being delt with in different issues.
Closing this one.

**Closed by ShiFoo** 2016-04-19 17:20 UTC
Labels: Medium Priority, Template
