### ISSUE TITLE
Investigate aircraft behaviour with ALiVE

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#258] opened 2016-01-24 17:53 UTC
The task is to get some more, detailed info on how good the UAVs work in ALiVE mission regarding AI spawning and overall behaviour.

**Comment by adios113** [comment] 2016-01-24 21:19
UAVs are treated like Aircrafts - by default they do not proc unit spawning.

**Comment by TheGrandVizier** [comment] 2016-01-26 14:10
@adios113 
Based on documentation, testing or both?

**Comment by Fourjays** [comment] 2016-01-26 15:06
Making this a general research topic on aircraft in ALiVE. Need to know where the limits are and what configuration options are available for aircraft (UAV/rotary/fixed) to play a role in ALiVE missions.

**Comment by adios113** [comment] 2016-01-26 22:43
@TheGrandVizier 
Based on testing and a chat with ALiVE's dev.

**Comment by adios113** [comment] 2016-01-27 12:28
Aight, so....
 We have 3 categories of player unit in ALiVE.
* Players on the ground (1500m)
* Players piloting helicopters (1500m)
* Players piloting Aircrafts+UAVs (0m)

All three have their separate spawn radius, which can be changed inside Virtual AI System Module.
Spawn Radius above 3km is considered to have an impact on server performance. The Distance from the players is measured in 3D, so the higher a helicopter is, the less will he spawn.

**Comment by Fourjays** [comment] 2016-01-27 18:46
Is it possible to prevent specific units from being cached? And retain the headless client offloading and AI commander?

Does the suggested spawn radius take headless clients into consideration? Unless the AI is very dense, I'd be surprised if two headless clients can't handle the AI requirements for a larger area.

**Comment by adios113** [comment] 2016-01-27 22:31
Yes. By default, only units synced to the Virtual AI Module are being profiled. That means units spawned in the editor normaly, are not being profiled, but you can change the option to profile them as well. `_vehicle setVariable ["ALIVE_profileIgnore", true];` - to ignore the unit from profiling.

I already asked about a possibility to make ALiVE manage the HC instead of WHK, the initial answer is positive, but I am still awaiting more detailed one - but that different topic, so as soon as I know more about this, I'll give you more.

By default, the main goal of ALiVE was to work without headless clients, just very recently they have added HC support and from what I know, it has not been fully implemented - issue like Player Combat Support not working properly with HC yet is a perfect example of that. Anyway, In my opinion a distance bigger than 1500 may be an overkill in terms of player's performance, which is very dependent on number of units spawned

**Comment by ShiFoo** [comment] 2016-01-28 09:12
Just to be clear: if you make an ALiVE mission, you have to disable WHK!

**Comment by Fourjays** [comment] 2016-01-28 09:24
ALiVE headless clients appear to be working as it logs the transfer of units to "HC_1". I have only seen entries for the first headless client though.

A radius of 1.5km is a tight limit for infantry (it's within view distance on some terrain), and is very small for air operations.

I want us to do some testing and further investigations. Need to determine where the limits are for the radius, and see what potential configuration options are available that may help make the AO more convincing for air assets.

**Comment by adios113** [comment] 2016-01-28 12:11
I am talking about Headless Client on the templates, not during ALiVE missions.
And ALiVE not utilisng HC_2 is probably effect of not completely finished support for HC's, as said in my last post. I'm in contact with ALiVE's devs, turned out one of them is someone who I know from other stuff, so we are in a pretty good contact. 

`Well, all you would need is the ALiVE (Required) module (no Virtual AI System) since it has no connection to virtual entities. I'll wait till Highhead gives his answer but I would assume yes since it loops through allGroups.` - ALiVE's dev.

Helicopters have their own spawn radius, so it shouldn't be a problem for them. Aircrafts will be targeting only targets assigned by ground forces. I am pretty confident, that if we increase the spawn radius for infantry, the performance hit will be too much. And the more units ALiVE loads at the same time - bigger chance for desync, cause that desync problem is not only tied to zeus. It's caused by too much units spawning/despawning on the map at the same time. And btw, Zeus should be used only for mission administration - teleports, other admin commands while runing an ALiVE mission - but that's only my personal opinion.

**Comment by ShiFoo** [comment] 2016-01-28 13:42
>At the end, I think we forgot about one major thing - It's all mission creator dependant what values he chooses in the end, we can only give him some tips. Still, I'm looking forward to how it goes if someone pulls the trigger with increased spawn radius.

Then he is responsible for fucking up his own mission by not listening to us = not our problem

**Comment by Fourjays** [comment] 2016-03-09 17:26
Think this can be closed as there isn't anything to research further.

**Closed by Fourjays** 2016-03-09 17:26 UTC
Labels: Medium Priority, Research
