### ISSUE TITLE
Remove inventory contents of spawned vehicles

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#356] opened 2016-03-19 22:53 UTC
All Zeus/editor spawned vehicles have an inventory full of random weapons, ammunition and supplies. This undermines the resupply system we're trying to impose. We'd like to investigate the possibility of forcing all vehicles to spawn with an empty inventory.

This should not interfere with elements that may be considered to be a vehicle contents, such as ACE cargo or our ammo resupply boxes.

**Comment by adios113** [comment] 2016-03-20 00:12
Did some research. We probably will have to utilise an Eventhandler. Best one I found so far is 

> CuratorObjectPlaced

and then remove the spawned vehicle's cargo via:

> clearItemCargoGlobal
> clearMagazineCargoGlobal
> clearBackpackCargoGlobal
> clearWeaponCargoGlobal

Btw. The reason the editor spawned boxes still spawn with objects, is because the wrong command has been used. You used the same command i wrote above, but the non MP synchronised version, without "global". Commands listed above will fixed the problem for editor spawned cargo holders.

**Comment by ShiFoo** [comment] 2016-03-21 10:55
I guess that the object placed can be somehow referenced in the function body. We have to get the classname, check it against a self-defined list of vehicles and then execute the code appropriately.

And the global commands of the commands are not needed for editor placed objects. Every client downloads the mission.sqm and executes the code locally. If you use the global ones, everytime a player joins the server he broadcasts the emtying of the boxes, which is unnecessary.
The actual problem was that the fix got somehow overwritten in the develop branch with the old init line. Now it has the correct commands and it is working as intended.

**Comment by TheGrandVizier** [comment] 2016-03-21 11:56
Not to be a party pooper, but we are also talking about Zeus-Placed object here, yes?

**Comment by ShiFoo** [comment] 2016-03-21 11:59
"CuratorObjectPlaced" is a mechanism that we can most likely use to modify objects placed by Zeus, yes. We were talking about two seperate things here.

**Comment by adios113** [comment] 2016-03-21 13:48
It possibly can be done trough usage of those commands: 
https://community.bistudio.com/wiki/vehicles
https://community.bistudio.com/wiki/isKindOf

trough an "if" statement.

```
_vehicles = vehicles;
	
	if(isKindof _vehicles) then {
		removecargo _x}
```
- Example script.
attached to the `curatorObjectPlaced` eventhandler

**Comment by ShiFoo** [comment] 2016-03-21 15:20
Exactly thats what i thought. This seems like a good solution.
Now you need the global ones though.

**Comment by Fourjays** [comment] 2016-03-21 15:40
Is the "vehicles" in this case definitely the type with wheels or tracks? From working on configs, a lot of items get "classified" as vehicles (typically anything with an inventory).

**Comment by adios113** [comment] 2016-03-21 16:29
Got a working version of a function:

### BWI_fnc_ClearCargo

`this addEventHandler ["CuratorObjectPlaced", {[_this select 1] call BWI_fnc_ClearCargo}];
`

This goes into Zeus Module's Init line - not zeus player.

> BWI_fnc_ClearCargo:
> 
> _vehicle = _this select 0;
> if((_vehicle isKindOf "landVehicle") or (_vehicle isKindOf "Air")) then
> 	{
> 		clearWeaponCargo _vehicle;
> 		clearMagazineCargo _vehicle;
> 		clearItemCargo _vehicle;
> 		clearBackpackCargo _vehicle;
> 	};
>

**Comment by TheGrandVizier** [comment] 2016-03-21 16:33
Now you got my appetite going. Is it possible for the reverse to be done? A
module that allows me to add shit to a cars inventory as I would a box? :)

**Comment by adios113** [comment] 2016-03-21 16:42
What you just described, has already been made possible in 3DEN editor. Might take some time to figure it out, because it might be more complex.

**Comment by TheGrandVizier** [comment] 2016-03-21 17:39
Everything I am asking, I am asking in zeus context.

**Comment by Fourjays** [comment] 2016-03-21 23:01
Given this a test run and it appears to be working fine. Need to think of some edge cases to check, but all vehicles have ammo for their guns, ACE systems work normally, spawned units are ignored and our ammoboxes are unaffected.

Couple of minor improvements that would be good:
- Remove the inventory for boats as well as land vehicles/aircraft.
- Apply the same to any editor spawned vehicles (for those who make editor missions).

**Comment by Fourjays** [comment] 2016-03-21 23:01
Converting this issue into an action item.

**Comment by TheGrandVizier** [comment] 2016-03-22 08:46
Oh, can we also utilize this to clear Armory box of vanilla content please?

**Comment by adios113** [comment] 2016-03-22 12:33
Progress:

- [x]  BWI_fnc_ClearCargoZeus

- [ ] BWI_fnc_ClearCargoEditor

- [ ] Zeus modules need to be named

- [ ] init.sqf edition

**Comment by ShiFoo** [comment] 2016-03-22 12:44
Couple of questions: Why are you wrapping those three commands into a function/actually two functions?
Is there a technical neccessity or just to give them a name?
What is a init.sqf edition?

**Comment by adios113** [comment] 2016-03-22 13:58
1. ClearCargoZeus is a function to be run everytime zeus object is placed thanks to `CuratorObjectPlaced `eventhandler

2. ClearCargoEditor is a function to be run on the mission start.

3. BWI_fnc_ClearCargoInit is a function which is responsible of adding the eventhandler to zeus modules, so that we don't have to run trough all the templates and add it to each module manualy.

4. initServer.sqf is required for Editor and Init function, to prevent JIP issues with Editor function (if its in init.sqf it will be called every single time player joins) and for Init function, since it only requires to be run once, because the function is attached to a logic, not player.

**Comment by Fourjays** [comment] 2016-03-22 14:54
Something we must test with this is how it behaves with JIPs. We don't want players to put something in an inventory, then somebody joins and either the inventory empties for them or everyone. From aDi's explanation that shouldn't be an issue, but we need to check.

**Comment by ShiFoo** [comment] 2016-03-22 18:27
JIP is not an issue as long as the clearCargo functions are not attached to the player object, which they currently aren't.
If i understand you correctly aDi, it should be good. You can push your changes and we can try it. I don't see any problem with it.

**Comment by adios113** [comment] 2016-03-22 20:19
Changes pushed to dev branch. You can check it out, iFu.

**Comment by ShiFoo** [comment] 2016-03-28 13:28
Changes are good. Closing.

**Closed by ShiFoo** 2016-03-28 13:28 UTC
Labels: Low Priority, Needs Testing, Template
