### ISSUE TITLE
Convert FOB and Medical Tent to addons

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#347] opened 2016-03-16 00:37 UTC
For reasons of maintainability, we would like future editions of the FOB and Medical Tent to be written as mods rather than template scripts.

Until the update and conversion is completed via #349, issues regards the FOB and Medical Tent will remain on this tracker. On closure of this issue, all further tracking of the FOB and Medical Tent will occur at: https://github.com/blackwatchint/addons/issues

Commits relating to these changes should occur on the new repository as well.

**Comment by Fourjays** [comment] 2016-03-16 01:04
The Armory could also be converted, but I think main concerns are whether it is more practical as a template script.

**Comment by ShiFoo** [comment] 2016-04-24 21:58
Tested with Abel and Nik. Working as intended. Closing

**Closed by ShiFoo** 2016-04-24 21:58 UTC
Labels: Medium Priority, Template
