### ISSUE TITLE
HLC G36 Rifle Family  

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#210] opened 2016-01-04 10:37 UTC
**Description:**
After reunification at the End of the Soviet Union, the re-formed Bundeswehr were in need of a standardised infantry weapon, and on a budget. 
H&K, being one of the preferred candidates on the tender, offered up numerous existing designs, all turned down. Design work was then initiated from the ground up on a modern 5.56mm assault rifle designated "Project 50" or HK50. The prototype was then trialed, where it was rated higher than the rival Austrian Steyr AUG system. The final version of the G36 was completed in 1994. Production of the G36 began in 1995.

Contents:
- 18 (!) different variations of the G36s, encompassing it's history and it's place in the fictional future of Arma3
- 8 scopes: two models, two different zoom levels, 2D versions
- ACE Advanced Ballistics support.
- Custom GL animations on top of regular ones.

**Download:** http://www.armaholic.com/page.php?id=30069
**Size:** 187 MB

**Comment by TheGrandVizier** [comment] 2016-01-04 11:44
I understand GL animations were changed in 1.54. Supported?
Do we not already have an assortment of german weapons we already do not use?

**Comment by abelarno** [comment] 2016-01-04 12:47
This was released only a couple of days ago (Date: 2015-12-29 09:31), so I assume it would be supported.
Reason for inclusion from the forums:
>I would like to see this mod included because the current G36 rifles take up way too much space in your screen and look pretty shitty in my opinion. 

I agree that we already have quite a lot of weapons, and I think we would need to have a good reason to add even more.

**Comment by Tebro** [comment] 2016-01-07 15:22
The pack works well. After testing them my opinion is that these look better than our current one, just as the quote from the forums mention.

Some screenshots I took can be found here: http://imgur.com/a/0utMg

**Comment by LordCavac** [comment] 2016-02-06 02:03
They look better than the current G36 and don't take up 1/5 of my screen which are both pluses. Testing them they preformed as well as any other 5.56 rifles.

A potentially major bug that I didn't experience personally but I read on the steam workshop page actually is that they couldn't hear people on their own team firing except in fully automatic mode, that was posted three days ago.

If that post isn't correct then I see no reason not to include this if we get rid of the current G36 pack. Assuming we even want the G36 at all, I think I've only seen them used twice in my months here and both times were dextero ops who seems to have stopped making them.

**Comment by Fourjays** [comment] 2016-04-03 14:07
There appears to be two basic variants of the G36s in this pack, with a number of specific variants between them. There are the basic G36s with the built-in handle/sight, which come with a selection non-interchangable scopes specific to the G36s. Then there is another version unfamiliar to me, which appears to take the normal rails-based scopes. All models are very well-made, with good sounds (albeit different from BWMod's) and some beautifully detailed animations.

All weapons appeared to function as expected. I couldn't reproduce the sound issue previously mentioned in singleplayer, so would recommend it be tested on the server before final inclusion, should it be accepted. Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=658625736
http://steamcommunity.com/sharedfiles/filedetails/?id=658625781
http://steamcommunity.com/sharedfiles/filedetails/?id=658625815
http://steamcommunity.com/sharedfiles/filedetails/?id=658625986
http://steamcommunity.com/sharedfiles/filedetails/?id=658625856
http://steamcommunity.com/sharedfiles/filedetails/?id=658625939
http://steamcommunity.com/sharedfiles/filedetails/?id=658626021
http://steamcommunity.com/sharedfiles/filedetails/?id=658626069
http://steamcommunity.com/sharedfiles/filedetails/?id=658626158
http://steamcommunity.com/sharedfiles/filedetails/?id=658626196

**Comment by abelarno** [comment] 2016-04-03 20:28
I've tested the mod without any issues. The weapons are very pretty, with good animations.
Most of the toughts I have about the quality of this mod has been written out already by others.

I do think that this pack serves very little use tough. As far as I know the current G36 weapons provided by both BW and CUP are sufficient, and using this mod would mostly be aesthetics based.
Unless ofcourse there is an issue with those weapons that I'm not aware of.

I don't think the size of the mod justifies the gains, and seeing that our current modpack is already over 32gb its my opinion that aesthetics should not be the driving force behind mod inclusions.

(Its gotten so big I can't even use my ssd anymore :-( )

**Comment by Fourjays** [comment] 2016-04-04 17:11
Accepted in the meeting on 04/04/2016.

**Comment by Fourjays** [comment] 2016-04-25 09:21
Was tested by @ShiFoo, @TheGrandVizier and @abelarno. No issues with the weapon sounds in multiplayer were found.

Closing as testing complete.

**Closed by Fourjays** 2016-04-25 09:21 UTC
Labels: Accepted, Modpack, Request
