### ISSUE TITLE
Investigate creation of custom units and groups

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/modpack#239] opened 2016-01-14 00:53 UTC
We want to look at the possibility of having custom spawnable groups, available for Zeus, MCC and ALiVE based operations (pending results of #232). Purpose would be to allow us to create our own aggressor units where desirable (e.g. Vietcong).

**Comment by blackwatchint** [comment] 2016-01-14 00:57
The following config.cpp is something I previously came up when testing this as a feasible concept, but it is pretty basic:
```sqf
class CfgPatches {
	class BWI_TEST_UNITS {
		requiredVersion = 1;
		author[] = { "Fourjays" };
		authorURL = "https://blackwatch-int.com";
		version = 0.0.1;
		versionStr = "0.0.1";
		versionAr[] = {0,0,0};
		requiredAddons[] = {};
		weapons[] = {};
		units[] = {"BWI_SOLDIER_A"};
	};
};

class CfgFactionClasses {
	class BWI_TEST_FACTION {
		displayName = "BWI Test Faction";
		priority = 8;
		side = 3;
	};
};

class CfgVehicleClasses {
	class BWI_VEHICLE_CLASS {
		displayName = "BWI Vehicle Class";
	};
};

class CfgVehicles {
	class Civilian;
	class Civilian_F : Civilian {
		class EventHandlers;	// External class reference
	};
		
	class BWI_SOLDIER_A : Civilian_F {
		scope = 2;
		scopeCurator = 2;
		faction = "BWI_TEST_FACTION";
		vehicleClass = "BWI_VEHICLE_CLASS";
		displayName = "BWI Test Solider";
		identityTypes[] = {"LanguageGRE_F", "Head_Asian", "G_CIVIL_male", "H_BandMask_blk", "NoGlasses"};
		canCarryBackPack=1;
		
		
		weapons[]=
		{
			"rhs_weap_ak74m_dtk",
			"rhs_weap_rsp30_red",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_ak74m_dtk",
			"rhs_weap_rsp30_red",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_mag_rgd5",
			"rhs_mag_rgd5",
			"rhs_mag_nspn_red"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_mag_rgd5",
			"rhs_mag_rgd5",
			"rhs_mag_nspn_red"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"rhs_6b27m",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"rhs_6b27m",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camob"
		};
	};
};
```

**Comment by Fourjays** [comment] 2016-01-14 00:58
The following config.cpp is something I previously came up when testing this as a feasible concept, but it is pretty basic:
```sqf
class CfgPatches {
	class BWI_TEST_UNITS {
		requiredVersion = 1;
		author[] = { "Fourjays" };
		authorURL = "https://blackwatch-int.com";
		version = 0.0.1;
		versionStr = "0.0.1";
		versionAr[] = {0,0,0};
		requiredAddons[] = {};
		weapons[] = {};
		units[] = {"BWI_SOLDIER_A"};
	};
};

class CfgFactionClasses {
	class BWI_TEST_FACTION {
		displayName = "BWI Test Faction";
		priority = 8;
		side = 3;
	};
};

class CfgVehicleClasses {
	class BWI_VEHICLE_CLASS {
		displayName = "BWI Vehicle Class";
	};
};

class CfgVehicles {
	class Civilian;
	class Civilian_F : Civilian {
		class EventHandlers;	// External class reference
	};
		
	class BWI_SOLDIER_A : Civilian_F {
		scope = 2;
		scopeCurator = 2;
		faction = "BWI_TEST_FACTION";
		vehicleClass = "BWI_VEHICLE_CLASS";
		displayName = "BWI Test Solider";
		identityTypes[] = {"LanguageGRE_F", "Head_Asian", "G_CIVIL_male", "H_BandMask_blk", "NoGlasses"};
		canCarryBackPack=1;
		
		
		weapons[]=
		{
			"rhs_weap_ak74m_dtk",
			"rhs_weap_rsp30_red",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"rhs_weap_ak74m_dtk",
			"rhs_weap_rsp30_red",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_mag_rgd5",
			"rhs_mag_rgd5",
			"rhs_mag_nspn_red"
		};
		respawnMagazines[]=
		{
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_30Rnd_545x39_7N10_AK",
			"rhs_mag_rgd5",
			"rhs_mag_rgd5",
			"rhs_mag_nspn_red"
		};
		Items[]=
		{
			"FirstAidKit"
		};
		RespawnItems[]=
		{
			"FirstAidKit"
		};
		linkedItems[]=
		{
			"rhs_6b27m",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"rhs_6b27m",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camob"
		};
	};
};
```

**Comment by abelarno** [comment] 2016-01-14 07:20
I worked on this before: https://github.com/justinilalonde/GOF_Units

We could just reuse that code.

**Comment by adios113** [comment] 2016-01-14 11:39
New Github Project has been created, focused on AddOns to prevent any kind of mess caused by having both templates and addon in on place.

https://github.com/blackwatchint/BWINT_Addons

Discussion will take place here, though.

**Comment by adios113** [comment] 2016-01-16 11:29
Since we will be using ALIVE, we have to make sure, that the config is compatible with it.
Here's an example of ALIVE compatible custom unit groups config.

http://alivemod.com/wiki/index.php/Unit_Mod_Config_Standardisation

**Comment by Fourjays** [comment] 2016-03-09 17:34
Closing as research stage complete. Future discussion on any custom units we plan to create will take place at https://github.com/blackwatchint/addons

**Closed by Fourjays** 2016-03-09 17:34 UTC
Labels: Modpack, Research
