### ISSUE TITLE
CUP Terrains

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#193] opened 2015-12-26 02:08 UTC
**Description:**
The Community Upgrade Project brings you CUP Terrains, the successor of "A3MP" and "All in ArmA - Terrain Pack (AiA TP)".
It builds upon the work done by kju for AiA TP and brings all of BI's iconic terrains to ArmA 3 as well as all the amazing 3rd-party terrains created by the community.
CUP Terrains maintains full backwards compatibility to A3MP and AiA TP - no need to adjust any missions or maps.

**Download:** http://www.armaholic.com/page.php?id=30045
**Size:** 7.58GB

**Comment by ShiFoo** [comment] 2015-12-28 09:17
Do i see it correctly, that  this would replace AiA? I am still wondering what the benefit of it is? Better quality? I alway thought that all CUP addons were of minor quality ( i just heard it, maybe a rumor ). Could you shed some light on this?

**Comment by Fourjays** [comment] 2015-12-28 10:19
Better quality (e.g. ponds work, street lights upgraded to Arma 3 standards) and reportedly no RPT errors (AiA fills the logs with messages). It is also the only actively developed terrain pack now, as both AiA and A3MP were abandoned. We wanted to switch to CUP Terrains a few months back, but it was producing a lot of errors with third party maps.

As such, it is important that we test for compatibility with all of our maps.

**Comment by ShiFoo** [comment] 2015-12-30 10:41
As far as i can see it works fine. I browsed through a couple of maps and i cant tell teh difference... I have check the RPT file afterwards and i did not find any errors. As for now: i only see that members had to download 7.7 GB without any benefit. It is __not__ working __better__ than AiA.

**Comment by wingatex** [comment] 2015-12-30 10:46
The other maps we also use like Chernarus Winter has been updated for CUP with minor changes of improvement

**Comment by Fourjays** [comment] 2015-12-31 19:44
We'll have to switch to it at some point in the future anyway regardless of any perceptible benefits, as AiA/A3MP are abandonware and new map releases/updates will utilise CUP.

**Comment by ShiFoo** [comment] 2015-12-31 22:31
Ok, with a little more testing we could do it in the next milestone.

**Comment by abelarno** [comment] 2016-01-01 14:36
I think I went trough all of the maps. Everything worked fine.
Also: ponds <3

**Comment by abelarno** [comment] 2016-01-03 11:20
This mod has been updated to 1.0.1

>Changelog:
*Added: Editor entries for A1 and A2 objects
*Added: Support for MapBuilder
*Fixed: Missing AiA TP compatibility entries
*Fixed: Wrong faction configuration leading to potential CTD when using 3DEN
*Fixed: Bargate rotated by 90° on ArmA2 maps
*Improved: Different signature keys for Core and Maps (Full will be signed with Core + Maps)

**Comment by abelarno** [comment] 2016-01-04 13:13
Something worth mentioning that im reading on the forums: 
When using fog with CUP terrains, the water in the ponds will be black. There is nothing CUP can do about this, since its an issue with the fog that bohemia needs to fix.

**Comment by Fourjays** [comment] 2016-02-15 11:03
This mod will be tested on the test server, as it will have a wide ranging impact on the rest of the modpack.

**Comment by Relvox** [comment] 2016-02-15 15:13
delegated to nik

**Comment by TheGrandVizier** [comment] 2016-02-16 12:46
Uploaded to repo

**Comment by Fourjays** [comment] 2016-03-04 13:24
All maps need testing for any problems caused by the switch from All in Arma to CUP Terrains.

**Comment by Fourjays** [comment] 2016-03-04 17:47
Issues noticed so far:
- Chernarus Winter ponds have small gaps in the surface.
- Lost Island and VT5 both missing ca/plants_e2 objects (All in Arma, no reference in CUP it seems).
- Lost Island missing ibr/dtowns objects (from Isla Duala, file is present so error is odd).

**Comment by Fourjays** [comment] 2016-03-09 14:36
- Missing ibr/dtowns was caused by an out of date file.
- Missing ca/plants_e2 seems to be because those objects are All In Arma only.

**Comment by Fourjays** [comment] 2016-03-09 15:48
These issues will be accepted as known issues. Closing as CUP Terrains is on the test repository waiting for live deployment.

**Closed by Fourjays** 2016-03-09 15:48 UTC
Labels: Modpack, Request
